name: Python CI with UV

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # This will spin up 3 separate virtual machines at the same time!
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Speeds up future runs!

      - name: Set up Python
        run: uv python install --python ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync # This looks at your pyproject.toml

      - name: Run Tests
        # We use pytest to find and run our test_main.py
        run: uv run pytest